import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from plotly.subplots import make_subplots

def get_simulated_sentiment(df):
    """
    Simulates sentiment data. In a real project, you would replace this
    with an NLP model analyzing real-time news/social media.
    """
    # Create a synthetic sentiment score based on daily returns + noise
    sentiment = df['Daily Return'].apply(lambda x: np.clip(x * 10 + np.random.normal(0, 0.1), -1, 1))
    df['Sentiment Score'] = sentiment.rolling(window=7).mean().fillna(0)  # Smooth it out
    return df


def show_sentiment_demo():
    """
    Shows a simple demo of the VADER sentiment analyzer.
    """
    st.subheader("Sentiment Analysis (NLP) Demo")
    st.write(
        "This project integrates NLP to gauge market sentiment. Here is a live demo using VADER, a sentiment analysis tool.")

    sid = SentimentIntensityAnalyzer()

    # Example headlines
    pos_headline = "Bitcoin hits new all-time high, huge gains for investors!"
    neg_headline = "Crypto market crashes, regulators investigating Binance."

    # Analyze and display
    st.markdown(f"**Positive Headline:** `{pos_headline}`")
    st.json(sid.polarity_scores(pos_headline))

    st.markdown(f"**Negative Headline:** `{neg_headline}`")
    st.json(sid.polarity_scores(neg_headline))


def show_sentiment_page(df):
    """
    Main function to display the sentiment page content.
    """
    st.header("Volatility & Sentiment Analysis")
    st.markdown("This section analyzes price fluctuations (volatility) and integrates NLP-based sentiment analysis.")

    # --- Visualization 1: Volatility Over Time ---
    st.subheader("Rolling 30-Day Volatility")
    st.line_chart(df['Volatility'], use_container_width=True)
    st.write(
        "Volatility measures the standard deviation of daily returns, indicating price stability. Higher values mean more risk and price fluctuation.")

    # --- Visualization 2: Simulated Sentiment Score vs. Price ---
    st.subheader("Simulated Sentiment Score vs. Price")
    st.write(
        "This chart plots the (simulated) daily market sentiment against the closing price. In a real-world application, this score would be generated by analyzing thousands of news articles and social media posts.")

    # --- NEW CODE (using graph_objects for dual-axis) ---
    # Create figure with secondary y-axis
    fig = make_subplots(specs=[[{"secondary_y": True}]])

    # Add Close Price trace (Primary Y-Axis)
    fig.add_trace(
        go.Scatter(x=df.index, y=df['Close'], name="Close Price (USD)"),
        secondary_y=False,
    )

    # Add Sentiment Score trace (Secondary Y-Axis)
    fig.add_trace(
        go.Scatter(x=df.index, y=df['Sentiment Score'], name="Sentiment Score"),
        secondary_y=True,
    )

    # Add figure title
    fig.update_layout(
        title_text="Price vs. Sentiment"
    )

    # Set x-axis title
    fig.update_xaxes(title_text="Date")

    # Set y-axes titles
    fig.update_yaxes(title_text="<b>Close Price (USD)</b>", secondary_y=False)
    fig.update_yaxes(title_text="<b>Sentiment Score</b>", secondary_y=True)

    st.plotly_chart(fig, use_container_width=True)

    # --- Live Demo ---
    show_sentiment_demo()

    # --- Visualization 3: Word Cloud (Demo) ---
    st.subheader("Sentiment Word Cloud Example")
    st.write(
        "A word cloud visually represents the most frequent and important words from text data. This would be used on news headlines.")

    example_text = "Bitcoin Ethereum profit gain bull market rally moon buy safe investment secure great opportunity loss risk scam bubble crash bear market sell warning dangerous volatile"

    try:
        wordcloud = WordCloud(width=800, height=400, background_color='black').generate(example_text)
        fig, ax = plt.subplots()
        ax.imshow(wordcloud, interpolation='bilinear')
        ax.axis('off')
        st.pyplot(fig)
    except Exception as e:
        st.error(f"Error generating word cloud: {e}")
